name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Test
      run: dotnet test
