name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: "codecov.xml"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: dotnet test

  testcov:
    runs-on: ubuntu-latest
    steps:
        - name: use this action, test solution dir
          uses: zyborg/dotnet-tests-report@v1
          with:
            project_path: 2k\HomeWork1\Hw1Tests
            report_name: my_project_tests
            report_title: My Project Tests
            github_token: ${{ secrets.GITHUB_TOKEN }}
